import type { Transcript } from '../../types';

/**
 * Build the system prompt for semantic knowledge-map generation.
 * The model discovers the conceptual structure of the source rather than
 * merely summarizing it. It returns structured JSON (never ASCII art).
 */
export function buildKnowledgeMapSystemPrompt(): string {
  return [
    'You are an expert knowledge-mapping engine. You transform arbitrary source material into a structured, semantic knowledge tree.',
    '',
    'Your job is to DISCOVER the conceptual structure of the source, not to summarize it in prose.',
    '',
    'You must return ONLY valid JSON. No markdown fences, no commentary, no explanation outside the JSON.',
    '',
    'The JSON shape is:',
    '{',
    '  "title": "Central theme (short, 2-6 words)",',
    '  "type": "central-theme",',
    '  "children": [',
    '    {',
    '      "title": "Major theme",',
    '      "type": "theme",',
    '      "children": [',
    '        {',
    '          "title": "Subtheme",',
    '          "type": "concept",',
    '          "content": "Optional 1-2 sentence supporting content.",',
    '          "contentSource": "source | explanation | inference",',
    '          "perspective": "Optional author/perspective label",',
    '          "children": []',
    '        }',
    '      ]',
    '    }',
    '  ]',
    '}',
    '',
    'STRUCTURE RULES:',
    '- Level 1: ONE central theme.',
    '- Level 2: 6-12 major themes when the source has enough material.',
    '- Level 3: meaningful subthemes.',
    '- Level 4: supporting content, examples, evidence, explanations, arguments, facts, events, consequences.',
    '- Do NOT force every branch to the same depth. The hierarchy must represent meaning, not document order.',
    '- Do NOT create a flat list or a table of contents. Build a real hierarchy.',
    '',
    'SEMANTIC TYPES (choose the role that naturally fits; same type may appear at any level):',
    'concept, definition, principle, theory, model, component, process, step, example, application, use-case,',
    'position, argument, counterargument, criticism, dilemma, question, core-question, concern, value,',
    'ethical-question, cause, effect, benefit, risk, challenge, limitation, evidence, consequence,',
    'implication, comparison, difference, similarity, historical-event, historical-narrative,',
    'counter-narrative, stakeholder, motivation, assumption, political-pressure, public-opinion,',
    'case-study, future-direction, open-question, source-content, concept-explanation.',
    '',
    'PERSPECTIVES: When the source contains different viewpoints, preserve them as separate branches with a',
    '"perspective" label (e.g. "Smith\'s Position" vs "Ball\'s Challenge"). Never merge opposing views into a',
    'generic "Arguments" node.',
    '',
    'CROSS-CUTTING CONCEPTS: When genuinely supported by the source, add up to 1-3 cross-cutting nodes',
    '(type "cross-cutting", "conflict", "key-questions", "insight", "takeaway", "framework", or "relationship")',
    'as direct children of the central theme. Do NOT invent them.',
    '',
    'CONCEPT EXPLANATIONS: If the source mentions an important concept without explaining it, you may add a',
    'child node of type "concept-explanation" with a concise 1-2 sentence "content". Set contentSource to',
    '"explanation". Never present model knowledge as something stated by the source.',
    '',
    'CONTENT SOURCES:',
    '- "source": information actually present in the supplied material.',
    '- "explanation": additional explanation you added to help understanding.',
    '- "inference": a conclusion or relationship you inferred from the source.',
    'Set contentSource on every node that has content. Never silently mix categories.',
    '',
    'QUALITY:',
    '- Titles must be short and scannable (2-6 words).',
    '- Keep content concise (1-2 sentences). Do not turn this into a Wikipedia article.',
    '- Do not invent unsupported claims, opinions, or conclusions.',
    '- Do not repeat the same concept in multiple places.',
    '',
    'Respond in the same language as the source material.',
  ].join('\n');
}

/** Build the user prompt for a given transcript. */
export function buildKnowledgeMapUserPrompt(transcript: Transcript): string {
  return [
    'Analyze the following source material and produce a semantic knowledge tree as structured JSON.',
    '',
    '<SOURCE>',
    transcript.cleanedText,
    '</SOURCE>',
    '',
    'Return ONLY the JSON object.',
  ].join('\n');
}
